name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test-matrix:
    runs-on: ubuntu-slim
    name: test (${{ matrix.ruby }})
    continue-on-error: ${{ matrix.optional }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '3.4'
            test_task: ci
            optional: false
          - ruby: head
            test_task: test
            optional: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          cache-version: 1
      - name: "Run tests (${{ matrix.test_task }})"
        run: bundle exec rake ${{ matrix.test_task }}
      - name: Generate RBS files from annotations
        if: matrix.ruby == '3.4'
        run: bundle exec rake rbs:generate
      - name: Upload coverage to Codecov
        if: matrix.ruby == '3.4' && always()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage.xml
          fail_ci_if_error: false
        continue-on-error: true
